### ISSUE TITLE
Wrong "Clear Key" system ID in PSSH generator

### ISSUE THREAD

**Issue by sandersaares** [Axinom/media-tools#4]
`1077efec-c0b2-4d02-ace3-3c1e52e2fb4b` is not the Clear Key system ID. The correct value is `e2719d58-a985-b3c9-781a-b030af78d30e`

Edit: However, as Clear Key does not have any defined PSSH format, perhaps it is the name that is wrong and not the ID?

**Comment by vladimir-kazakov** [comment]
Yes, the name is wrong.
